module.exports={	
  mysql:{	
    host:'localhost',	
    user:'root',	
    password:'23456789',	
    database:'ezdb',	
    port:3306	
  },	
  server:{	
    url:"http://loaclhost:8000",	
    host:"localhost",	
    port:8000	
  },	
  pageStep:5,	
  cookieName:'azeBlog',	
} 
