export const actionType = {
  GET_SEARCH_KEY: "GET_SEARCH_KEY",
  SET_SEARCH_PREVIEW: "SET_SEARCH_PREVIEW",
  SET_SEARCH_RESULT: "SET_SEARCH_RESULT",

  GET_ARTICLE_LIST: "GET_ARTICLE_LIST",
  SET_ARTICLE_LIST: "SET_ARTICLE_LIST",

  GET_ARTICLE_DETAIL:"GET_ARTICLE_DETAIL",
  SET_ARTICLE_DETAIL: "SET_ARTICLE_DETAIL",
  ADD_ARTICLE: "ADD_ARTICLE",
  UPDATE_ARTICLE: "UPDATE_ARTICLE",
  DELETE_ARTICLE: "DELETE_ARTICLE",

  GET_CATEGORY_LIST:"GET_CATEGORY_LIST",
  SET_CATEGORY_LIST:"SET_CATEGORY_LIST",
  ADD_CATEGORY: "ADD_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",

  GET_COMMENT_LIST:"GET_COMMENT_LIST",
  SET_COMMENT_LIST:"SET_COMMENT_LIST",
  ADD_COMMENT:"ADD_COMMENT",

  SET_MESSAGE: "SET_MESSAGE",

  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SET_USER_INFO: "SET_USER_INFO",  
  GET_USER_LIST: "GET_USER_LIST",
  SET_USER_LIST: "GET_USER_LIST",
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
}